
ABBEVILLE     = "Abbeville"
AMIENS        = "Amiens"
ANTWERP       = "Antwerp"
BREMEN        = "Bremen"
BREST         = "Brest"
CHERBOURG     = "Cherbourg"
EMDEN         = "Emden"
HAMM          = "Hamm"
KIEL          = "Kiel"
LA_ROCHELLE   = "La Rochelle"
LILLE         = "Lille"
LORIENT       = "Lorient"
MEAULTE       = "Meaulte"
PARIS         = "Paris"
RENNES        = "Rennes"
ROMILLY_SUR_SEINE = "Romilly-sur-Seine"
ROTTERDAM     = "Rotterdam"
ROUEN         = "Rouen"
ST_OMER       = "St. Omer"
ST_NAZAIRE    = "St. Nazaire"
VEGESACK      = "Vegesack"
WILHELMSHAVEN = "Wilhelmshaven"

AIRFIELD  = "Airfield"
AIRCRAFT  = "Aircraft"
RAIL_YARD = "Rail Yard"
SHIP_YARD = "Ship Yard"
INDUSTRY  = "Industry"

WATER = "W"
FRANCE = "F"
BELGIUM = "B"
GERMANY = "G"
NETHERLANDS = "N"

OUT = "Out"
BACK = "Back"

OUT_OF_FORMATION = "Out of Formation"
LESS_THAN_10000_FT = "<= 10,000 ft"

BAD  = "Bad"
POOR = "Poor"
FAIR = "Fair"
GOOD = "Good"

HIGH   = "High"
MIDDLE = "Middle"
LOW    = "Low"
LEVEL  = "Level"

LEAD_BOMBER = "Lead Bomber"
TAIL_BOMBER = "Tail Bomber"

NO_FLAK = "No Flak"
LIGHT_FLAK = "Light Flak"
MEDIUM_FLAK = "Medium Flak"
HEAVY_FLAK = "Heavy Flak"

HIT = "Hit"
MISS = "Miss"

# Crew Status
OK            = "OK"
LIGHT_WOUND   = "Light Wound"
SERIOUS_WOUND = "Serious Wound"
KIA           = "Killed-In-Action"

# Guns
NOSE        = "Nose"
TOP_TURRET  = "Top Turret"
BALL_TURRET = "Ball Turret"
TAIL_TURRET = "Tail Turret"
STBD_CHEEK  = "Starboard Cheek"
STBD_WAIST  = "Starboard Waist"
PORT_CHEEK  = "Port Cheek"
PORT_WAIST  = "Port Waist"
RADIO       = "Radio"

# Crew Member Roles
BOMBARDIER        = "Bombardier"
NAVIGATOR         = "Navigator"
PILOT             = "Pilot"
COPILOT           = "Copilot"
ENGINEER          = "Engineer"
RADIO_OPERATOR    = "Radio Operator"
BALL_GUNNER       = "Ball Gunner"
PORT_WAIST_GUNNER = "Port Waist"
STBD_WAIST_GUNNER = "Starboard Waist"
TAIL_GUNNER       = "Tail Gunner"

# Plane Areas (including NOSE)
PILOT_COMPARTMENT  = "Pilot Compartment"
BOMB_BAY           = "Bomb Bay"
RADIO_ROOM         = "Radio Room"
WAIST              = "Waist"
TAIL               = "Tail"
PORT_WING          = "Port Wing"
STBD_WING          = "Starboard Wing"
SUPERFICIAL_DAMAGE = "Superficial Damage"

# Landing Effects
CREW_KIA = "Crew KIA"
CREW_ROLL_FOR_WOUNDS_PLUS_ONE = "Crew rolls for wounds (+1)"
CREW_ROLL_FOR_WOUNDS = "Crew rolls for wounds"
CREW_SAFE = "Crew Safe"
CREW_LOST = "Crew lost"
CREW_RESCUED = "Crew rescued"
CREW_CAPTURED = "Crew captured"
BOMBER_WRECKED = "B-17 Wrecked"
BOMBER_REPAIRABLE = "B-17 repairable by next mission"
BOMBER_SAFE = "B-17 Safe"

# Enemy Fighters
FIGHTER_109 = "Me 109"
FIGHTER_110 = "Me 110"
FIGHTER_190 = "Fw 190"

AREA_12 = "12"
AREA_1_30 = "1:30"
AREA_3 = "3"
AREA_6 = "6"
AREA_9 = "9"
AREA_10_30 = "10:30"
VERTICAL_CLIMB = "Vertical Climb"
VERTICAL_DIVE = "Vertical Dive"

# German fighter damage
FCA = "Fighter damaged but continues attack at -1"
FBOA = "Fighter damaged and breaks off after this attack -2"
DESTROYED = "Fighter destroyed and may not fire at B-17"


# Bomber Damage Type
NO_EFFECT = "No effect"
NORDEN_SIGHT = "Norden Sight"
NOSE_GUN_INOPERABLE = "Nose Gun Inoperable"
PORT_CHEEK_INOPERABLE = "Port Cheek Gun Inoperable"
STBD_CHEEK_INOPERABLE = "Starboard Cheek Gun Inoperable"
BOMBARDIER_AND_NAVIGATOR_HIT = "Bombardier and Navigator Hit"
NAVIGATOR = "Navigator Hit"
BOMBARDIER = "Bombardier Hit"
NAVIGATOR_EQUIPMENT_INOPERABLE = "Navigator Equipment Inoperable"
BOMB_CONTROLS_INOPERABLE = "Bomb Controls Inoperable"
BOMBARDIER_HEAT_OUT = "Bombardier Heat Out"
NAVIGATOR_HEAT_OUT = "Navigator Heat Out"
BOMBARDIER_AND_NAVIGATOR_HEAT_OUT = "Bombardier and Navigator Heat Out"
BOMBARDIER_OXYGEN_HIT = "Bombardier Oxygen Hit"
NAVIGATOR_OXYGEN_HIT = "Navigator Oxygen Hit"
BOMBARDIER_AND_NAVIGATOR_OXYGEN_HIT = "Bombardier and Navigator Oxygen Hit"
FIRE_AND_NOSE_OXYGEN_OUT = "Fire and Nose Oxygen Out"
PILOT_AND_COPILOT_HEAT_OUT = "Pilot and Copilot Heat Out"
PILOT_AND_COPILOT_HIT = "Pilot and Copilot Hit"
TOP_TURRET_INOPERABLE = "Top Turret Inoperable"
TOP_TURRENT_INOPERABLE_AND_ENGINEER_HIT = "Top Turret Inoperable and Engineer Hit"
INSTRUMENTS = "Instruments"
PILOT_AND_COPILOT_OXYGEN_HIT = "Pilot and Copilot Oxygen Hit"
PILOT_OXYGEN_HIT = "Pilot Oxygen Hit"
COPILOT_OXYGEN_HIT = "Copilot Oxygen Hit"
ENGINEER_OXYGEN_HIT = "Engineer Oxygen Hit"
FIRE_AND_PILOT_COMPARTMENT_OXYGEN_OUT = "Fire and Pilot Compartment Oxygen Hit"
WINDOW = "Window Hit"
CONTROL_CABLES = "Control Cables Hit"
BOMBS_DROP_MANUALLY = "Bombs Drop Manually"
BOMBS_DETONATE = "Bombs Detonate"
RUBBER_RAFTS_HIT = "Rubber Rafts Hit"
BOMB_BAY_DOORS_INOPERABLE = "Bomb Bay Doors Inoperable"
RADIO_ROOM_HEAT_OUT = "Radio Room Heat Out"
INTERCOM_SYSTEM_OUT = "Intercom System Out"
RADIO_OUT = "Radio Out"
RADIO_ROOM_OXYGEN_HIT = "Radio Room Oxygen Hit"
FIRE_AND_RADIO_ROOM_OXYGEN_OUT = "Fire and Radio Room Oxygen Out"
PORT_WAIST_OXYGEN_HIT = "Port Waist Oxygen Hit"
STBD_WAIST_OXYGEN_HIT = "Starboard Waist Oxygen Hit"
BALL_GUNNER_OXYGEN_HIT = "Ball Gunner Oxygen Hit"
FIRE_AND_WAIST_OXYGEN_OUT = "Fire and Waist Oxygen Out"
PORT_WAIST_GUN_INOPERABLE = "Port Waist Gun Inoperable"
STBD_WAIST_GUN_INOPERABLE = "Starboard Waist Gun Inoperable"
BALL_GUNNER_HEAT_OUT = "Ball Gunner Heat Out"
BALL_TURRET_INOPERABLE = "Ball Turret Inoperable"
BALL_TURRET_MECHANISM_INOPERABLE = "Ball Turret Mechanism Inoperable"
PORT_WAIST_GUNNER_AND_STBD_WAIST_GUNNER_HIT = "Port and Starboard Waist Gunners Hit"
PORT_WAIST_GUNNER_HEAT_OUT = "Port Waist Gunner Heat Out"
STBD_WAIST_GUNNER_HEAT_OUT = "Starboard Waist Gunner Heat Out"
TAIL_GUNNER_HEAT_OUT = "Tail Gunner Heat Out"
TAIL_WHEEL_DAMAGED = "Tailwheel Damaged"
AUTOPILOT_INOPERABLE = "Autopilot Inoperable"
TAIL_TURRET_INOPERABLE = "Tail Turret Inoperable"
RUDDER = "Rudder Hit"
PORT_ELEVATOR_INOPERABLE = "Port Elevator Inoperable"
STBD_ELEVATOR_INOPERABLE = "Starboard Elevator Inoperable"
PORT_TAILPLANE_ROOT_HIT = "Port Tailplane Root Hit"
STBD_TAILPLANE_ROOT_HIT = "Starboard Tailplane Root Hit"
TAIL_OXYGEN_HIT = "Tail Oxygen Hit"
FIRE_AND_TAIL_OXYGEN_OUT = "Fire and Tail Oxygen Out"
