package b17.game;

public enum PhaseStep {
    START_PHASE,
    END_PHASE,

    PLAY_MISSION_MOVE_NEXT_ZONE,
    PLAY_MISSION_FIGHTER_WAVE,
    PLAY_MISSION_FIGHTER_WAVE_ATTACK,
    PLAY_MISSION_FIGHTER_WAVE_ATTACK_CONTINUE,
    PLAY_MISSION_FIGHTER_WAVE_ATTACK_FIGHTER_DEFENSE,
    PLAY_MISSION_FIGHTER_WAVE_ATTACK_B17_PLACE_FIRE,
    PLAY_MISSION_FIGHTER_WAVE_ATTACK_B17_FIRE,
    PLAY_MISSION_FIGHTER_WAVE_ATTACK_GERMAN_FIRE,
    PLAY_MISSION_ANTIAIRCRAFT_FIRE,
    PLAY_MISSION_BOMB_RUN,
    PLAY_MISSION_LANDING
}
